SELECT
    JSON_VALUE(data, '$.id') as id,
    CAST(JSON_VALUE(data, '$.version') as INT64) as version,
    CAST(JSON_VALUE(data, '$.created_at') as TIMESTAMP) as created_at,
    CAST(JSON_VALUE(data, '$.modified_at') as TIMESTAMP) as modified_at,
    CAST(JSON_VALUE(data, '$.abs_diff') as INT64) as abs_diff,
    JSON_VALUE(data, '$.account_id') as account_id,
    JSON_VALUE(data, '$.action') as action,
    CAST(JSON_VALUE(data, '$.collateral_amount') as INT64) as collateral_amount,
    JSON_VALUE(data, '$.credit_facility_id') as credit_facility_id,
    JSON_VALUE(data, '$.custody_wallet_id') as custody_wallet_id,
    JSON_VALUE(data, '$.audit_entry_ids') as audit_entry_ids,
    JSON_VALUE(data, '$.ledger_tx_ids') as ledger_tx_ids,
    _sdc_extracted_at as _sdc_extracted_at,
    _sdc_deleted_at as _sdc_deleted_at,
    _sdc_received_at as _sdc_received_at,
    _sdc_batched_at as _sdc_batched_at,
    _sdc_table_version as _sdc_table_version,
    _sdc_sequence as _sdc_sequence,
from {{ source("lana", "public_core_collateral_events_rollup") }}
