SELECT
    JSON_VALUE(data, '$.id') as id,
    CAST(JSON_VALUE(data, '$.version') as INT64) as version,
    CAST(JSON_VALUE(data, '$.created_at') as TIMESTAMP) as created_at,
    CAST(JSON_VALUE(data, '$.modified_at') as TIMESTAMP) as modified_at,
    JSON_VALUE(data, '$.account_to_be_debited_id') as account_to_be_debited_id,
    CAST(JSON_VALUE(data, '$.amount') as INT64) as amount,
    JSON_VALUE(data, '$.credit_facility_id') as credit_facility_id,
    JSON_VALUE(data, '$.effective') as effective,
    JSON_VALUE(data, '$.ledger_tx_id') as ledger_tx_id,
    JSON_VALUE(data, '$.obligation_id') as obligation_id,
    CAST(JSON_VALUE(data, '$.obligation_installment_idx') as INT64) as obligation_installment_idx,
    JSON_VALUE(data, '$.obligation_type') as obligation_type,
    JSON_VALUE(data, '$.payment_id') as payment_id,
    JSON_VALUE(data, '$.receivable_account_id') as receivable_account_id,
    JSON_VALUE(data, '$.audit_entry_ids') as audit_entry_ids,
    _sdc_extracted_at as _sdc_extracted_at,
    _sdc_deleted_at as _sdc_deleted_at,
    _sdc_received_at as _sdc_received_at,
    _sdc_batched_at as _sdc_batched_at,
    _sdc_table_version as _sdc_table_version,
    _sdc_sequence as _sdc_sequence,
from {{ source("lana", "public_core_obligation_installment_events_rollup") }}
