SELECT
    JSON_VALUE(data, '$.id') as id,
    CAST(JSON_VALUE(data, '$.version') as INT64) as version,
    CAST(JSON_VALUE(data, '$.created_at') as TIMESTAMP) as created_at,
    CAST(JSON_VALUE(data, '$.modified_at') as TIMESTAMP) as modified_at,
    JSON_VALUE(data, '$.account_ids') as account_ids,
    CAST(JSON_VALUE(data, '$.amount') as INT64) as amount,
    JSON_VALUE(data, '$.approval_process_id') as approval_process_id,
    CAST(JSON_VALUE(data, '$.approved') as BOOLEAN) as approved,
    JSON_VALUE(data, '$.disbursal_credit_account_id') as disbursal_credit_account_id,
    JSON_VALUE(data, '$.due_date') as due_date,
    JSON_VALUE(data, '$.effective') as effective,
    JSON_VALUE(data, '$.facility_id') as facility_id,
    JSON_VALUE(data, '$.ledger_tx_id') as ledger_tx_id,
    JSON_VALUE(data, '$.liquidation_date') as liquidation_date,
    JSON_VALUE(data, '$.obligation_id') as obligation_id,
    JSON_VALUE(data, '$.overdue_date') as overdue_date,
    JSON_VALUE(data, '$.public_id') as public_id,
    JSON_VALUE(data, '$.audit_entry_ids') as audit_entry_ids,
    CAST(JSON_VALUE(data, '$.is_approval_process_concluded') as BOOLEAN) as is_approval_process_concluded,
    CAST(JSON_VALUE(data, '$.is_cancelled') as BOOLEAN) as is_cancelled,
    CAST(JSON_VALUE(data, '$.is_settled') as BOOLEAN) as is_settled,
    _sdc_extracted_at as _sdc_extracted_at,
    _sdc_deleted_at as _sdc_deleted_at,
    _sdc_received_at as _sdc_received_at,
    _sdc_batched_at as _sdc_batched_at,
    _sdc_table_version as _sdc_table_version,
    _sdc_sequence as _sdc_sequence,
 from {{ source("lana", "public_core_disbursal_events_rollup") }}
