SELECT
    JSON_VALUE(data, '$.id') as id,
    CAST(JSON_VALUE(data, '$.version') as INT64) as version,
    CAST(JSON_VALUE(data, '$.created_at') as TIMESTAMP) as created_at,
    CAST(JSON_VALUE(data, '$.modified_at') as TIMESTAMP) as modified_at,
    JSON_VALUE(data, '$.credit_facility_id') as credit_facility_id,
    JSON_VALUE(data, '$.effective') as effective,
    JSON_VALUE(data, '$.in_liquidation_account_id') as in_liquidation_account_id,
    CAST(JSON_VALUE(data, '$.initial_amount') as INT64) as initial_amount,
    JSON_VALUE(data, '$.ledger_tx_id') as ledger_tx_id,
    JSON_VALUE(data, '$.obligation_id') as obligation_id,
    JSON_VALUE(data, '$.audit_entry_ids') as audit_entry_ids,
    CAST(JSON_VALUE(data, '$.is_completed') as BOOLEAN) as is_completed,
    _sdc_extracted_at as _sdc_extracted_at,
    _sdc_deleted_at as _sdc_deleted_at,
    _sdc_received_at as _sdc_received_at,
    _sdc_batched_at as _sdc_batched_at,
    _sdc_table_version as _sdc_table_version,
    _sdc_sequence as _sdc_sequence,
from {{ source("lana", "public_core_liquidation_process_events_rollup") }}
