SELECT
    JSON_VALUE(data, '$.id') as id,
    CAST(JSON_VALUE(data, '$.version') as INT64) as version,
    CAST(JSON_VALUE(data, '$.created_at') as TIMESTAMP) as created_at,
    CAST(JSON_VALUE(data, '$.modified_at') as TIMESTAMP) as modified_at,
    CAST(JSON_VALUE(data, '$.amount') as INT64) as amount,
    JSON_VALUE(data, '$.credit_facility_id') as credit_facility_id,
    JSON_VALUE(data, '$.defaulted_account_id') as defaulted_account_id,
    CAST(JSON_VALUE(data, '$.defaulted_amount') as INT64) as defaulted_amount,
    JSON_VALUE(data, '$.defaulted_date') as defaulted_date,
    JSON_VALUE(data, '$.due_accounts') as due_accounts,
    CAST(JSON_VALUE(data, '$.due_amount') as INT64) as due_amount,
    JSON_VALUE(data, '$.due_date') as due_date,
    JSON_VALUE(data, '$.effective') as effective,
    JSON_VALUE(data, '$.in_liquidation_account_id') as in_liquidation_account_id,
    CAST(JSON_VALUE(data, '$.initial_amount') as INT64) as initial_amount,
    JSON_VALUE(data, '$.liquidation_date') as liquidation_date,
    JSON_VALUE(data, '$.liquidation_process_id') as liquidation_process_id,
    JSON_VALUE(data, '$.not_yet_due_accounts') as not_yet_due_accounts,
    CAST(JSON_VALUE(data, '$.obligation_installment_amount') as INT64) as obligation_installment_amount,
    JSON_VALUE(data, '$.obligation_type') as obligation_type,
    JSON_VALUE(data, '$.overdue_accounts') as overdue_accounts,
    CAST(JSON_VALUE(data, '$.overdue_amount') as INT64) as overdue_amount,
    JSON_VALUE(data, '$.overdue_date') as overdue_date,
    JSON_VALUE(data, '$.payment_id') as payment_id,
    JSON_VALUE(data, '$.reference') as reference,
    JSON_VALUE(data, '$.audit_entry_ids') as audit_entry_ids,
    JSON_VALUE(data, '$.ledger_tx_ids') as ledger_tx_ids,
    JSON_VALUE(data, '$.obligation_installment_ids') as obligation_installment_ids,
    CAST(JSON_VALUE(data, '$.is_completed') as BOOLEAN) as is_completed,
    CAST(JSON_VALUE(data, '$.is_defaulted_recorded') as BOOLEAN) as is_defaulted_recorded,
    CAST(JSON_VALUE(data, '$.is_due_recorded') as BOOLEAN) as is_due_recorded,
    CAST(JSON_VALUE(data, '$.is_overdue_recorded') as BOOLEAN) as is_overdue_recorded,
    _sdc_extracted_at as _sdc_extracted_at,
    _sdc_deleted_at as _sdc_deleted_at,
    _sdc_received_at as _sdc_received_at,
    _sdc_batched_at as _sdc_batched_at,
    _sdc_table_version as _sdc_table_version,
    _sdc_sequence as _sdc_sequence,
from {{ source("lana", "public_core_obligation_events_rollup") }}
