SELECT
    JSON_VALUE(data, '$.id') as id,
    CAST(JSON_VALUE(data, '$.version') as INT64) as version,
    CAST(JSON_VALUE(data, '$.created_at') as TIMESTAMP) as created_at,
    CAST(JSON_VALUE(data, '$.modified_at') as TIMESTAMP) as modified_at,
    CAST(JSON_VALUE(data, '$.amount') as INT64) as amount,
    JSON_VALUE(data, '$.approval_process_id') as approval_process_id,
    CAST(JSON_VALUE(data, '$.approved') as BOOLEAN) as approved,
    JSON_VALUE(data, '$.deposit_account_id') as deposit_account_id,
    JSON_VALUE(data, '$.reference') as reference,
    JSON_VALUE(data, '$.status') as status,
    JSON_VALUE(data, '$.audit_entry_ids') as audit_entry_ids,
    JSON_VALUE(data, '$.ledger_tx_ids') as ledger_tx_ids,
    CAST(JSON_VALUE(data, '$.is_approval_process_concluded') as BOOLEAN) as is_approval_process_concluded,
    CAST(JSON_VALUE(data, '$.is_cancelled') as BOOLEAN) as is_cancelled,
    CAST(JSON_VALUE(data, '$.is_confirmed') as BOOLEAN) as is_confirmed,
    _sdc_extracted_at as _sdc_extracted_at,
    _sdc_deleted_at as _sdc_deleted_at,
    _sdc_received_at as _sdc_received_at,
    _sdc_batched_at as _sdc_batched_at,
    _sdc_table_version as _sdc_table_version,
    _sdc_sequence as _sdc_sequence,
from {{ source("lana", "public_core_withdrawal_events_rollup") }}
