SELECT
    JSON_VALUE(data, '$.id') as id,
    CAST(JSON_VALUE(data, '$.version') as INT64) as version,
    CAST(JSON_VALUE(data, '$.created_at') as TIMESTAMP) as created_at,
    CAST(JSON_VALUE(data, '$.modified_at') as TIMESTAMP) as modified_at,
    JSON_VALUE(data, '$.account_ids') as account_ids,
    CAST(JSON_VALUE(data, '$.activated_at') as TIMESTAMP) as activated_at,
    CAST(JSON_VALUE(data, '$.amount') as INT64) as amount,
    JSON_VALUE(data, '$.approval_process_id') as approval_process_id,
    CAST(JSON_VALUE(data, '$.approved') as BOOLEAN) as approved,
    CAST(JSON_VALUE(data, '$.collateral') as INT64) as collateral,
    JSON_VALUE(data, '$.collateral_id') as collateral_id,
    JSON_VALUE(data, '$.collateralization_ratio') as collateralization_ratio,
    JSON_VALUE(data, '$.collateralization_state') as collateralization_state,
    JSON_VALUE(data, '$.customer_id') as customer_id,
    JSON_VALUE(data, '$.disbursal_credit_account_id') as disbursal_credit_account_id,
    CAST(JSON_VALUE(data, '$.interest_accrual_cycle_idx') as INT64) as interest_accrual_cycle_idx,
    JSON_VALUE(data, '$.interest_period') as interest_period,
    JSON_VALUE(data, '$.outstanding') as outstanding,
    JSON_VALUE(data, '$.price') as price,
    JSON_VALUE(data, '$.public_id') as public_id,
    JSON_VALUE(data, '$.terms') as terms,
    JSON_VALUE(data, '$.audit_entry_ids') as audit_entry_ids,
    JSON_VALUE(data, '$.interest_accrual_ids') as interest_accrual_ids,
    JSON_VALUE(data, '$.ledger_tx_ids') as ledger_tx_ids,
    JSON_VALUE(data, '$.obligation_ids') as obligation_ids,
    CAST(JSON_VALUE(data, '$.is_activated') as BOOLEAN) as is_activated,
    CAST(JSON_VALUE(data, '$.is_approval_process_concluded') as BOOLEAN) as is_approval_process_concluded,
    CAST(JSON_VALUE(data, '$.is_completed') as BOOLEAN) as is_completed,
    _sdc_extracted_at as _sdc_extracted_at,
    _sdc_deleted_at as _sdc_deleted_at,
    _sdc_received_at as _sdc_received_at,
    _sdc_batched_at as _sdc_batched_at,
    _sdc_table_version as _sdc_table_version,
    _sdc_sequence as _sdc_sequence,
from {{ source("lana", "public_core_credit_facility_events_rollup") }}
