SELECT
    JSON_VALUE(data, '$.id') as id,
    CAST(JSON_VALUE(data, '$.version') as INT64) as version,
    CAST(JSON_VALUE(data, '$.created_at') as TIMESTAMP) as created_at,
    CAST(JSON_VALUE(data, '$.modified_at') as TIMESTAMP) as modified_at,
    JSON_VALUE(data, '$.account_ids') as account_ids,
    CAST(JSON_VALUE(data, '$.accrued_at') as TIMESTAMP) as accrued_at,
    CAST(JSON_VALUE(data, '$.amount') as INT64) as amount,
    JSON_VALUE(data, '$.effective') as effective,
    JSON_VALUE(data, '$.facility_id') as facility_id,
    JSON_VALUE(data, '$.facility_maturity_date') as facility_maturity_date,
    CAST(JSON_VALUE(data, '$.idx') as INT64) as idx,
    JSON_VALUE(data, '$.obligation_id') as obligation_id,
    JSON_VALUE(data, '$.period') as period,
    JSON_VALUE(data, '$.terms') as terms,
    CAST(JSON_VALUE(data, '$.total') as INT64) as total,
    JSON_VALUE(data, '$.tx_ref') as tx_ref,
    JSON_VALUE(data, '$.audit_entry_ids') as audit_entry_ids,
    JSON_VALUE(data, '$.ledger_tx_ids') as ledger_tx_ids,
    CAST(JSON_VALUE(data, '$.is_interest_accruals_posted') as BOOLEAN) as is_interest_accruals_posted,
    _sdc_extracted_at as _sdc_extracted_at,
    _sdc_deleted_at as _sdc_deleted_at,
    _sdc_received_at as _sdc_received_at,
    _sdc_batched_at as _sdc_batched_at,
    _sdc_table_version as _sdc_table_version,
    _sdc_sequence as _sdc_sequence,
from {{ source("lana", "public_core_interest_accrual_cycle_events_rollup") }}
