SELECT
    JSON_VALUE(data, '$.journal_id') as journal_id,
    JSON_VALUE(data, '$.account_id') as account_id,
    JSON_VALUE(data, '$.latest_entry_id') as latest_entry_id,
    JSON_VALUE(data, '$.currency') as currency,
    CAST(JSON_VALUE(data, '$.version') as INT64) as version,
    JSON_VALUE(data, '$.values') as values,
    CAST(JSON_VALUE(data, '$.recorded_at') as TIMESTAMP) as recorded_at,
    _sdc_extracted_at as _sdc_extracted_at,
    _sdc_deleted_at as _sdc_deleted_at,
    _sdc_received_at as _sdc_received_at,
    _sdc_batched_at as _sdc_batched_at,
    _sdc_table_version as _sdc_table_version,
    _sdc_sequence as _sdc_sequence,
from {{ source("lana", "public_cala_balance_history") }}
