query depositConfig {
  depositConfig {
    chartOfAccountsOmnibusParentCode
    chartOfAccountsIndividualDepositAccountsParentCode
    chartOfAccountsGovernmentEntityDepositAccountsParentCode
    chartOfAccountPrivateCompanyDepositAccountsParentCode
    chartOfAccountBankDepositAccountsParentCode
    chartOfAccountFinancialInstitutionDepositAccountsParentCode
    chartOfAccountNonDomiciledIndividualDepositAccountsParentCode
    chartOfAccountsFrozenIndividualDepositAccountsParentCode
    chartOfAccountsFrozenGovernmentEntityDepositAccountsParentCode
    chartOfAccountFrozenPrivateCompanyDepositAccountsParentCode
    chartOfAccountFrozenBankDepositAccountsParentCode
    chartOfAccountFrozenFinancialInstitutionDepositAccountsParentCode
    chartOfAccountFrozenNonDomiciledIndividualDepositAccountsParentCode
  }
}
