query TermsTemplateGet($id: UUID!) {
  termsTemplate(id: $id) {
    termsId
    name
    values {
      annualRate
      accrualCycleInterval
      duration {
        period
        units
      }
      liquidationCvl {
        ... on FiniteCVLPct {
          value
        }
        ... on InfiniteCVLPct {
          isInfinite
        }
      }
      marginCallCvl {
        ... on FiniteCVLPct {
          value
        }
        ... on InfiniteCVLPct {
          isInfinite
        }
      }
      initialCvl {
        ... on FiniteCVLPct {
          value
        }
        ... on InfiniteCVLPct {
          isInfinite
        }
      }
    }
  }
}
